spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor_db?useSSL=false
    username: root
    password: rootadmin

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# JPA Setting
  jpa.hibernate.ddl_auto: create